Typing and export PresenceError
TenType/discord-rich-presence pull request #3
Opened 2023-05-21 12:27 UTC by Amund211

Just upstreaming some more of the changes I've made in my copy of your library (https://github.com/Amund211/prism/commit/358bd76b86efe83ed393b6482587d761ae742fb2), though a bit less invasive this time. Feel free to pick and choose which commits you want or don't want.

Summary of the changes:
- Made explicit that `Presence` is exported from `__init__.py` (`mypy` was complaining about this)
- Added some more type hints in `presence.py` to make it pass `mypy --strict` (there are still some `Any` types and 1 call to `cast`
- Added a `py.typed` marker. This makes the type hints visible to people using the library, as before you would get an error that the module was installed, but could not be type-checked
- Added `PresenceError` as an export from `__init__.py`
- Fix type-checking on windows
- Always do platform check the same way (ref last commit)

2023-05-21 12:34 UTC, Amund211 commented
For the `sys.platform` thing I tried keeping the variable `WINDOWS` so we don't have to duplicate the string literal everywhere, but `mypy` didn't like it.
https://github.com/Amund211/prism/commit/70ebb79b3c5cad55379a11046d24aafd72ebc488: https://github.com/Amund211/prism/actions/runs/5037578368/jobs/9034513970
https://github.com/Amund211/prism/commit/d918bea15204557ff692f17f5e05ee10e0b4abab: https://github.com/Amund211/prism/actions/runs/5037594511/jobs/9034540744

2023-05-22 20:14 UTC, TenType commented
Thanks for all the help. Right now I am occupied with work but I'll take a look at it when I get the chance.

2023-06-04 07:55 UTC, TenType reviewed
Sorry for the delay! At this point, I think it would be better if separate socket classes were made for both platforms to avoid leaving the `socket` typed as `Any`. I kept your commits but also added my own refactoring. From my end on MacOS, it's still `mypy --strict` compliant, but let me know if it doesn't work for you or if you have any suggestions.

2023-06-04 22:45 UTC, TenType requested changes
Prefer `Optional[T]` over `Union[T, None]`

2023-06-04 22:45 UTC, TenType commented on discordrp/presence.py
> +from typing import Any, Union, cast
```suggestion
from typing import Any, Optional, cast
```

2023-06-04 22:45 UTC, TenType commented on discordrp/presence.py
> +    def set(self, activity: Union[dict[str, Any], None]) -> None:
```suggestion
    def set(self, activity: Optional[dict[str, Any]]) -> None:
```

2023-06-04 22:45 UTC, TenType commented on discordrp/presence.py
> +        exc_traceback: Union[TracebackType, None],
```suggestion
        exc_type: Optional[type[BaseException]],
        exc_value: Optional[BaseException],
        exc_traceback: Optional[TracebackType],
```

2023-06-04 22:52 UTC, Amund211 commented
Separate socket classes might be the cleanest option. We're still left with errors from `mypy` on windows, but that's just because the logic that chooses the `_Socket` implementation is way to advanced for `mypy` to understand. See: https://github.com/Amund211/discord-rich-presence/actions/runs/5171453202

Adding a `# type: ignore` just gives errors on the unicies because it's not a type error there lmao. `# type: ignore [attr-defined,unused-ignore]` [should work in the next release of `mypy`](https://github.com/python/mypy/issues/8823#issuecomment-1556288015), other than that I don't really know how to fix it. Then again, I don't think client code is affected by internal type errors in a library anyway, so it might be just okay to leave it, at least until the next `mypy` version. If that sounds OK to you you can cherry pick this: 4e6e497ff6a9e7b83b7670aac22870eb97b847fa.

Also, when adding the action to test the typing on windows I realized that I broke python 3.9 compatibility with the new union syntax, so I changed it to the old one in 0a5623c717d0e2a29220fb6da43866045c6a2b5c.

:^)

2023-06-04 22:52 UTC, Amund211 commented
> Prefer `Optional[T]` over `Union[T, None]`

Fair, I'll just change the commit and force push

2023-06-05 02:39 UTC, TenType commented
Thanks! I'll use `# type: ignore [attr-defined,unused-ignore]` for now then.

2023-06-05 02:41 UTC, TenType approved these changes

2023-06-05 02:42 UTC, merged